### ISSUE TITLE
AutoDestroy Rules

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#545]
Many units can autodestroy with large radius explosion. 
Can we fix the autodestruction period to 10s for them & 5s for others (except for mines)

Can you change some periods for ?
- Hero (5s) => 10s
- Fury (20s) => 10s
- All Commander (5s ~ 20s) => 10s
- ...

**Comment by SoulRaiZor** [comment]
what about hero 30s
fury 20s
commanders between 5s and 25s

**Comment by skymyj** [comment]
After 15 seconds, you can't predic if autodestroy will be good or bad.
So it's no more strategic but random.

**Comment by SoulRaiZor** [comment]
if one can destroy a hero, it should at least leave him a wreck.

**Comment by nixtux** [comment]
Check bottom of post for self-d count down timer

Only problem i see if countdown time missing for hero's (due to large aoe and damage from explosion)
and tllshark should have it timer set to 0 (all bomb type unit should)

Reducing time too much will be bad imo (smaller time's are easy to control for combomb)

armamex.lua:	selfDestructCountdown = 1,
armbanth.lua:	selfDestructCountdown = 10,
armcom1.lua:	selfDestructCountdown = 20,
armcom4.lua:	selfDestructCountdown = 20,
armcom5.lua:	selfDestructCountdown = 20,
armcom6.lua:	selfDestructCountdown = 20,
armcom7.lua:	selfDestructCountdown = 20,
armcom.lua:	selfDestructCountdown = 4,
armcrabe.lua:	selfDestructCountdown = 10,
armfmine3.lua:	selfDestructCountdown = 0,
arm_furie.lua:	selfDestructCountdown = 20,
armjag.lua:	selfDestructCountdown = 10,
armmcv.lua:	selfDestructCountdown = 10,
armmex1.lua:	selfDestructCountdown = 1,
armmex.lua:	selfDestructCountdown = 1,
armmine1.lua:	selfDestructCountdown = 0,
armmine2.lua:	selfDestructCountdown = 0,
armmine3.lua:	selfDestructCountdown = 0,
armmine5.lua:	selfDestructCountdown = 0,
armmine6.lua:	selfDestructCountdown = 0,
armmine7.lua:	selfDestructCountdown = 0,
armorco.lua:	selfDestructCountdown = 10,
armpeep.lua:	selfDestructCountdown = 1,
armspy.lua:	selfDestructCountdown = 1,
armtabi.lua:	selfDestructCountdown = 10,
armuwmex.lua:	selfDestructCountdown = 1,
armvader.lua:	selfDestructCountdown = 0,
corcom1.lua:	selfDestructCountdown = 20,
corcom3.lua:	selfDestructCountdown = 20,
corcom5.lua:	selfDestructCountdown = 20,
corcom6.lua:	selfDestructCountdown = 20,
corcom7.lua:	selfDestructCountdown = 20,
corcom.lua:	selfDestructCountdown = 4,
corexp.lua:	selfDestructCountdown = 1,
corfink.lua:	selfDestructCountdown = 1,
corflu.lua:	selfDestructCountdown = 10,
corfmine3.lua:	selfDestructCountdown = 0,
corkrog.lua:	selfDestructCountdown = 10,
cormex1.lua:	selfDestructCountdown = 1,
cormex.lua:	selfDestructCountdown = 1,
cormine1.lua:	selfDestructCountdown = 0,
cormine2.lua:	selfDestructCountdown = 0,
cormine3.lua:	selfDestructCountdown = 0,
cormine5.lua:	selfDestructCountdown = 0,
cormine6.lua:	selfDestructCountdown = 0,
cormine7.lua:	selfDestructCountdown = 0,
corpyro.lua:	selfDestructCountdown = 1,
corroach.lua:	selfDestructCountdown = 0,
corsktl.lua:	selfDestructCountdown = 0,
corspy.lua:	selfDestructCountdown = 1,
coruwmex.lua:	selfDestructCountdown = 1,
krogtaar.lua:	selfDestructCountdown = 10,
macross.lua:	selfDestructCountdown = 10,
terraunit.lua:  selfDestructCountdown  = 1,
tllcom3.lua:	selfDestructCountdown = 20,
tllcom5.lua:	selfDestructCountdown = 20,
tllcom6.lua:	selfDestructCountdown = 20,
tllcom7.lua:	selfDestructCountdown = 20,
tllcom.lua:	selfDestructCountdown = 4,
tllcrawlb.lua:	selfDestructCountdown = 1,
tllmine1.lua:	selfDestructCountdown = 0,
tllmine2.lua:	selfDestructCountdown = 0,
tllmine3.lua:	selfDestructCountdown = 0,
tllmine4.lua:	selfDestructCountdown = 0,
tllmine5.lua:	selfDestructCountdown = 0,
tllmine6.lua:	selfDestructCountdown = 0,
tllshark.lua:	selfDestructCountdown = 2,
