### ISSUE TITLE
T2.5 Nuke again?

### ISSUE THREAD

**Issue by SoulRaiZor** [n3wm1nd/TA#558]
Hi!
What about doing T2.5 nuke again which needs 2.5 protector?
ATM there is no sense in morphing a nuke.

**Comment by SoulRaiZor** [comment]
Maybe that u need 2 T2 anties firing parallel, or 1 T2.5 anti

**Comment by skymyj** [comment]
-Amunition load quicker. 
- Quicker : It let less time for antinuke to fir &  if you shoot on side limit antinuke. (10% from side in circle zone), antinuke can't intercept => I think.
-more domage

**Comment by SoulRaiZor** [comment]
All wrong.
we still have a bug that it loads even slower.
anti will hit in circle
more damage doesnt matter - its all dead even with normal nuke

**Comment by skymyj** [comment]
More damage & aoe

**Comment by SoulRaiZor** [comment]
So i can use two normal silencer too, cost is almost equal

**Comment by konecat** [comment]
ARM t2.5 nuke loads every 1 minute, not upgraded 2 minutes.

Core t2.5 nuke loads every 3 minutes,  not upgraded 2 minutes. (More dmg/AOE instead)

Guess which people would rather upgrade and why.
I also agree with the whole t2.5 anti-nuke needed to defend against t2.5 nuke. I thought it's like that when I began playing TA. It adds to the thrill and a little to a gameplay. So that's a good choice.

I'd propose T2 anti range cutting by 70% if fired at with T2.5 nuke. If anti is t2.5, range is saved (+ the longer range of t2.5anti). 

Also make it possible to defend against t2.5 with upgraded mobile anti as well. 

I think it'd make it interesting.

**Comment by skymyj** [comment]
We need an easy structure that don't penalize new players or players that didn't know T2.5 Nuke. (sickening to be atomized after +45min play).

I propose a T2.5 Nuke with more dmg/AOE, load in 2 minutes. 
Strategy to use it : counter attack T2.5/T3 with a large radius & dmg..  (They actually don't stop these units.) 1 shoot will inflict like 30~40k dmg to a bantha.

So T2 nuke : vs structure & T1/T2 units
T2.5 nuke : vs structure & T2.5/t3 units

**Comment by SoulRaiZor** [comment]
skys idea sounds good.
With 70% is hard to show ppl ingame.

**Comment by nixtux** [comment]
WOW OMG so you two are finally agreeing on something :D

**Comment by skymyj** [comment]
It happens :)

**Comment by nixtux** [comment]
Closing due to rework
