### ISSUE TITLE
We need a new balancing system

### ISSUE THREAD

**Issue by SoulRaiZor** [n3wm1nd/TA#561]
Hey!
We absolutely need a new balancing system which works better.
Only balancing TS points isnt working in ta.

For example it mixes 
TS38, TS20, TS20, TS20, TS13

with
TS30, TS25, TS25, TS25, TS15

of course this was a short game in 1v4.
-------------------------------------------------------------------------

My idea:
We need at least 4 Player categories:

1. Players > TS30
2. Players > TS25
3. Players > TS20
4. all other players and newcomers

Now how will balancing work like this? 
-------------------------------------------------------------------------
(best case)
- each team should have equal players from each category
--> balanced game

Example: 
TS30, TS25, TS20, TS15, TS13
vs
TS30, TS25, TS20, TS15, TS15
-------------------------------------------------------------------------

-------------------------------------------------------------------------
(normal case)
- each team have equal players in all possible categories.
- if its not possible to make this possible in 1 category do following
 Team 1: gets player from better category
 Team 2: gets 2 player from lower category

Rest can be filled up with normal TS balancing

Example:
TS30, TS25, TS25, TS15, TS13
vs
TS30, TS25, TS20, TS20, TS15
-------------------------------------------------------------------------

-------------------------------------------------------------------------
(worst case)
- only 1 player from cat 1 and some 3 or such
Following rules should fit good:
1 cat1 player == ~1.5 cat2 player
1 cat1 player == ~2.5 cat3 player

1 cat2 player == ~1.5 cat1 player

Example:
TS30, TS(10-15)*
vs
TS15, TS15, (TS15)*

or

TS30, TS20, (TS15)*
vs
TS20, TS20, TS20, (TS15)*

*(...) are optional
-------------------------------------------------------------------------

If u guys like something like this tell me and i invest more work in it.
Maybe 5 categories?
Nix can tell me in what language this should be written, so i can do it.

Greetz

**Comment by SoulRaiZor** [comment]
dunny why some words are bold, i didnt.

**Comment by konecat** [comment]
Because you used formatting which makes titles, apparently.

Anyway, this is a good idea, but works like communism - only on paper and not when dealing with humans. Soul's explanations are pretty fucking confusing and needlessly complicated.

Usually, TSkill just equalized based on TSkill and nothing else. TS30 and 3xTS10  is equal to 2xTS30.

That's a problem, because those TS10 noobs are basically non-players. In reality, TS for first team is like TS35 and for second is TS60 in total. But well, TS doesn't care. 

Problem is not with the system itself, but the way it calculates your skill. The scale is fucked up. It's Fahrenheit mixed with Celsius and treated like it's the same shit.

What we need is something MORE PRECISE in deciding what is what.

Ever saw something like TS 10? I never did. Lower I came across was 16. What's the point, when the scale doesn't begin from 0 ? Why is it so inaccurate for new players? They should gain  TS with time, not lose it with time. If it started from 0, this problem would never happen. Very dumb, unless you're defending yourself against smurfs.

Thing is, Soul is trying to circumvent around this. Do you really want that? Just make it start from 0. If you play badly enough, then sorry man, but your TS will be below 0 unless you fight your way out of it.

TS should also never be counted based on whether you win or not, but on statistics, such as how fast vs. rest of the players (and of which TS)you got your eco, damage inflicted, metal vs. dmg efficency, distribution etc.. Something like you have on the end of the round in XTA, and based on that, count the actual skill.

Then we could talk about accurate balance. Other than that, you might get something better than current, shitty TSkill, but nothing amazing.

**Comment by SoulRaiZor** [comment]
U are almost saying, what i wrote above.
I guess u didnt understood it.

And starting from 0 for new players is a bad idea.

Now u give them a middle skill and its finding its way with playing.
so u have a max difference from ~15TS points (Range 10-35)

If u let them start from 0 u have a max. difference from 35TS points, but at least 10 points (TS10)
So u get unbalanced games for sure.

Just my 2 cents

**Comment by nixtux** [comment]
Sorry to say this after such a nice long post, but I have no way to control the way spads balances games, you could add issue to spads bug tracker but I have no idea how far you will get, for now closing issue as I can't fix, just ask if you need link to spads bug tracker
