### ISSUE TITLE
Balance Dark Matter Converter

### ISSUE THREAD

**Issue by Senna** [n3wm1nd/TA#929]
Ive PM nixtux since 2 weeks, but he seems to be very busy, i dunno.

Dark Matter TLL t3 fusion needs an balance, they are crap right now

**Comment by Senna** [comment]
Ive been talking with nixtux 2 weeks about this change, but he seems ignore me completely

**Comment by nixtux** [comment]
I did ask you to pm other account which you didn't do, no history there, I wanted to get release out for rimpler fix too many ppl complained, I didn't even finishing adding new unit so don't worry there will be another release soon

**Comment by nixtux** [comment]
Senna btw now you got your password back you can fork repo and make your own pull request with changes all from github, would take 5 mins to get set up

**Comment by Gambit99** [comment]
What evidence says they are not good / effective?

**Comment by Senna** [comment]
15% effective against 25% afus, and explodes 4 times bigger

**Comment by skymyj** [comment]
effective what ? Please, give us stats. thanks

**Comment by Senna** [comment]
its an efficiency e/m in stats during game
higher better, for esample mega fus has 30%

**Comment by Gambit99** [comment]
Also, TLL T2 was nerfed extremely heavily some time in the last six months. They had a T2 lab for ~2k metal and a T2 con for ~800m. Now it is 4k / 2k like the ARM and CORE costs. This is just too high since their T2 units are (and should be) slightly less efficient than the ARM and CORE T2 analogues.

Since the goal here is to improve their late game eco, I'd like to suggest bringing back their cheaper T2 tech instead. Perhaps a price point of 2.5k/800. Slightly more expensive than before but not unreasonably high as it is now. The prices for these items follow the idea that TLL need T2 earlier in order to respond to ARM and CORE T1.5. It also gives them the economic head-start they need in order to climb to T3 faster since ARM and CORE additionally have stronger units at T2.5. The price of the con reflects the fact that it must also build their static defenses like a fark or consul. Their assistant is really only a mobile nano.

Again, I am following the notion discussed in lobby that, roughly speaking,
Std.T1 < TLL T1 < Std.T1.5 < TLL T2 < Std. T2 < Std. T2.5 < TLL T3 < Std. T3. 

If you disagree with this, then please say so because it is important that we all agree on this big picture when discussing balance changes. Maybe I am not thinking the same as everyone else. The central idea for their late game is that their units are not as strong, but they have faster economic development.

If the cheaper T2 lab is reinstated, then their T3 will also indirectly be buffed since it will come earlier. If we try to buff both stages of the game independently, the result will be an overpowered T3 phase that is also benefiting from some T2 phase buff.

**Comment by Zonkspring** [comment]
"Again, I am following the notion discussed in lobby that, roughly speaking,
Std.T1 < TLL T1 < Std.T1.5 < TLL T2 < Std. T2 < Std. T2.5 < TLL T3 < Std. T3.

If you disagree with this, then please say so"

So. :D 

About tll eco: Well, if you mouse over it and press space it shows automatically calculated efficency.
For Darkmatter its 15.68%, at first I thought the widget doesn't work right!!!
Then I look at Super Heavy Elemental - 17.63%. Wtf? Still bad, but better than Darkmatter Reactor?
Next I look at Regular Heavy Elemental - 21.08%. Ok, thats almost as good as normal Arm/Core fusion. 
And better than the more High-Tech options Super Heavy Elemental and Darkmatter. 
And alot smaller Explosion too.

In this comparison I will just convert 100% of Energy to Metal, makes it less complicated:
1 Darkmatter + 3 MMetalmaker = 222.6 Metal/Sec produced for 96638 Cost, 1855k buildtime.
= 434 cost & 8333 buildtime to produce 1 Metal/Sec.
VS
21 Heavy Elemental + 11 MMetalMaker = 237.3 Metal/Sec produced for 94085 Cost, 1855k buildtime.
= 396 cost & 7817 buildtime to produce 1 Metal/Sec.

Its not just Darkmatter that needs a buff but also Superheavy, it is also worse than Heavy Elemental.

Heavy Elemental itself is ok I think, its a bit worse than Arm/Core Fus but its supposed to be like that.
So as Gambit said, I think Superheavy should be a bit better than Arm/Core Fus but not as good as Arm/Core Afus.
Darkmatter better than Afus, worse than Megafus.

**Comment by Gambit99** [comment]
I'm not sure how the widget is calculating efficiency there. It could very well be wrong since TLL reactors also produce metal. Senethril, read this post. I think I have found some legitimacy to your argument.

The way I would calculate efficiency as (metal produced per second) / (metal cost).

For tllcoldfus (their t2 afus): this is = 21/13950 = 1.5e-3
For tllmegacoldfus (their t3 fusion): this is 180/89000 = 2.0e-3

To me it looks like the tllmegacoldfus is very metal efficient. Let's try the same calculation for energy with (energy produced per second) / (energy cost).

tllcoldfus: 2500/29850=8.4e-2
tllmegacoldfus: 14500/230000=6.3e-2

So here we have a case that the tllmegacold fus is less energy efficient than the tll coldfus. 

Finally, there is the buildtime. Given that tllmegacoldfus produces ~9 times more metal and ~7 times more energy than the tllcoldfus, you would expect it to have a buildtime somewhere *below* that neighbourhood in order to be considered "fast". In fact, its build time is 1750000 compared to 220000 of the tllcoldfus. That is a factor of 7.9. Not close to the bottom end of that range but certainly not out of reason. 

However, when you consider that the comparable tllcoldfus units **produce** energy in the same time that it would take you to complete the full tllmegafus, it turns out that the tllcoldfus units are producing even more energy overall than their raw output suggests. So, this is justification for Senethril's claim. So it might be that tllmegacoldfus needs a buff, although by the above calculations I would not apply this buff to its metal production, only its energy production.

**Comment by skymyj** [comment]
+1 with Gambit. Just increase energy production please. Metal production is good balanced.

**Comment by nixtux** [comment]
@Gambit99  https://github.com/n3wm1nd/TA/blob/master/luaui/widgets/gui_unit_stats_techa.lua#L248  read from there onwards to see how efficiency is calculated

**Comment by nixtux** [comment]
@Senna "15% effective against 25% afus, and explodes 4 times bigger"  you can't compare tll combo fusion v normal fusion they produce metal as well, thoses stats only compare energy output to metal+energy cost of units, which will allways be low as most of the energy from that unit is used to produce metal, I wonder how many afus + MM you need to match megacoldfus

**Comment by Gambit99** [comment]
My read of that widget is that it is basing the efficiency score (roughly) on energyProduced / (metalCost + energyCost + ...) . This is appropriate for pure energy producers but in the TLL case it is misleading since the building also produces metal.

The metalCost and energyCost of a TLL "combo" fus or afus are higher because they are getting both an energy producer and metal maker/converter in one. To the widget, it just looks like a very expensive fusion and thus the computed energy efficiency score is terrible.

If anything, this is a bug in the widget since it should be calculating efficiency differently for a TLL fus or afus. It already makes such provisions for other classes like tidal, wind, and the basic t1 solar, so we should really just re-file this as a bug in the widget rather than making drastic changes to TLL economy.

**Comment by Zonkspring** [comment]
@nixtux  I wonder how many afus + MM you need to match megacoldfus
I already did the math for that ingame / tested it, but i lost my notes... time to do all of it again I guess. Argh!

**Comment by Gambit99** [comment]
I have added a related issue about the widget in #965

**Comment by Zonkspring** [comment]
@nixtux  "I wonder how many afus + MM you need to match megacoldfus."
I've already tested this but I somehow lost my notes. :D time to do all of it again I guess... argh!

Ok, here we go:
2x tllmegacoldfus 185667 costs, 3500k Buildtime, Production: 29k E, 360 M
9x cafus + 23x cormmkr 167272 costs, 3444k Buildtime, Production: 28,8k E, 376.8M
So its pretty clear that Afus are a good deal better than Darkmatter for the cost.

And as Gambit said, no matter if we compare the Darkmatters to Afus or to Heavy Elementals, all of those smaller energy sources will - apart from the advantages in efficency they already have over Darkmatters - also produce energy (and m) bit by bit. 
When ur darkmatter is just at 60%, still producing zero E & M, your first 3 Afus will already be done, already producing about 9k Energy.
This by itself is not that dramatic, normal arm/core t2 fuses also have this advantage over Afus - but the Afus get higher total efficency to make up for it.

Heres another thing I just noticed, since Gambit & nixtux just mentioned that the Widget is calculating efficency incorrectly.
If it works that way.... then wait a moment, the widget shows the efficency of Heavy Elementals wrong too, since it only uses their E output/cost to calculate their efficency. 
And yet their efficency is at 21%, compared to corfus 23%. 
And thats all without taking the Metal income into the calculation.

- Theory: 
Its not just that Darkmatters are worse than Afus, the Heavy Elemental are also a bit OP.
So TLL eco is even more screwed than we thought. :D 

- Testing the Theory:
10x tllmedfusion 38080 costs, 700k buildtime, Production: 8000 E, (-3000E) 42 Metal
8x armfus + 3x cormmkr 42085 costs, 688k buildtime, Production: 8000 E, (-3072 E) 49.2 Metal

- Conclusion: 
Noticeably better than Arm/Core regular fuses. If we aim to make tllmedfus slightly worse than Arm/Core T2.0 Fuses, then tllmedfus need a small nerf.

OK, next on the TLL eco checklist:
The TLL Superheavy Elemental Reactor - tllcoldfus.
2x tllcoldfus 28895 costs, 440k Buildtime, Production: 5000 E, (-3000E) 42 Metal
5x armfus + 3x cormmkr 28889 costs,  484k Buildtime, Production: 5000 E, (-3072 E) 49,2 Metal
- Conclusion:
If we want to make Superheavys slightly better than Arm/Core T2.0 Fuses, they need a very minor buff. Right now they are slightly worse. 

What else is there to balance in TLL eco? 

Well, theres the completely oddball Underwater Heavy Elementals.
2x tlluwfusion 11688 costs,180k Buildtime, Production: 3000 E, (-1200) 12 Metal
1x aafus 11879 costs, 200k Buildtime, Production: 3000 E
1x aafus + 1x coruwmmm 15068 costs, 2036 Buildtime, Production: 3000 E, (-1280) 21.8 Metal

Okay, so they are more efficent than A-fus at making E but have a terribly inefficent built-in Energy-Metal Converter (just 10m/1000e). 
Those are not just in need of a nerf, but also of some rebalancing I think.

Question is how good should they be? 
Better or worse than Arm/Core UW-Fus?
I'd say for sure they should be worse than Arm/Core UW-Afus (crnns, armuwfus1) but perhaps better than arm/core normal uw-fus (armuwfus, coruwfus) since TLL doesnt get the UW-Afus.
Opinions on this?

**Comment by skymyj** [comment]
You can say many thing for balancing Tll constructor (for senna commits) OR FOR THIS SUBJECT WITH adv fusion.. but don't forget than no need to spend 50km + 18km + .... (Tech center 1.2.3.4 + t3 cons) to have access to mega fusion. Same for adv fusion, the t2 cons is cheaper than arm core. So I m fell good to have disbalance between tll and other faction.

**Comment by Zonkspring** [comment]
No question, tllmegacoldfus Darkmatter should be worse than Megafus Arm/Core because Megafus are much more expensive to make (Research Tree) than Darkmatter.

But at the same time, Darkmatter should also be a bit better than Arm/Core Afus, because its more expensive to make than Afus.

For Arm Afus u need T2 Vehicle Plant  5312 (can be recycled for -3915) + Cons 4051 
= total cost 5448 to make Afus
For Darkmatter u need T2 Vehicle Plant 5368 (can be recycled for -4653) + Cons 2564 (u can recycle it also but then u have smaller buildmenu AND worse eco than Arm with normal t2 cons) + Experimental Vehicle Plant (20317, can be recycled for -17900) + High Tech Construction Vehicle 15000
= total cost 20696 (and a lot more time to recycle two labs instead of one)

Almost 4x as much costs to make Darkmatter over Afus, not to mention time to build/recycle factorys.
The moment you just finish your High Tech Construction Vehicle from your Experimental Vehicle Plant (total cost "stuck" in buildings and cons at this moment: 35317) the Arm Player already has finished 3 Afus for same cost.

So Darkmatter really should be a bit better than Afus.

**Comment by Gambit99** [comment]
I agree with skymyj there ... there are many other economic factors besides the raw energy and metal efficiencies to take into account. Having played TLL quite a few times I think that their late game eco development is very healthy and even slightly faster that arm or core on maps with many metal spots.

**Comment by Senna** [comment]
and whats with the explosion then?
