### ISSUE TITLE
TLL Side t1 cons

### ISSUE THREAD

**Issue by Senna** [n3wm1nd/TA#933]
TLL t1 cons needs also an buff, they are expensive as hell and theyr buildtimes are very low

**Comment by Zonkspring** [comment]
+1 
Maybe not so much the Kbotcons (it costs 60 more than arm cons, has almost double the buildtime but has 10 more BP, 240 more hp and is 6 faster. 
Still, it might need a small buff maybe +10 bp?
Then it has the same as tll vehcons - same as with Arm and Core where veh and kbot also have same bp).
Or reduce buildtime (maybe 6000 ->  about 4500).

OR - Option 3 and this is my favourite - give it both, the +10 bp and the ~ 4500 Buildtime, because both are fitting changes - and take away some of its speed ( - 10?), its TLL, they are not supposed to be faster than Arm or Core I think.

In addition to either one of those Options I would lower E-costs a tiny bit. 
For Arm/Core, Vehcons have slightly higher E-costs than Kbotcons in Arm/Core, for TLL its the other way around? I would suggest E-Costs 2750 -> 2138.
So overall a bit of buffing and some rebalancing.

=====================================

The vehcons thought is really bad.
Costs 101 more, has 328 hp less, is 11 slower and the only thing it gets for all those drawbacks is 25 more buildpower.
3 Arm Vehcons cost less than 2 TLL Vehcons and have more Buildpower, a lot more HP and more speed.
Could do lower cost, could do more HP, could do more speed, could do more BP. Many ways to fix it.
Those Boxy wheels dont look like they belong on a Racecar, so I would just lower M cost (229m -> 179m) and give them a good bit more HP (912 -> 1315).
Some serious buffing/cost reductions in these two things, but I think its really needed.

Hover Air Sea cons I haven't really looked at yet, gotta sleep now. :)
Maybe I post more about those tomorrow or so, or maybe by then someone else will look over them ^^

**Comment by Gambit99** [comment]
I just want to point out that 25 more build power is a significant advantage. An ordinary arm kbot con has 90 workertime (build power). So tll are around 28% faster at building. That is quite large.

**Comment by Zonkspring** [comment]
It is, but it really depends on total costs/buildpower in the end.

I was wondering where you got the 25 Buildpower from but I think I see now... from vehcons, not kbotcons. Mmhmm. Well, my suggestion was based on raising the bp for Kbot by 10 - to a total of 20 more than Arm/Core.

So lets say we do those changes -> 
T1 TLL Kbot cons 110 bp, lower E costs and thus lower total costs (185), ~ 4500 Buildtime 
= 1.68 costs & 40 bt / 1 BP
T1 Core Kbot cons 90 bp, 150 cost, 3551 BT = 1.67 costs & 39 bt / 1 BP
T1 Arm Kbot cons 90 bp, 136 cost, 3543 BT = 1.51 costs & 39 bt / 1 BP

TLL KbotCons also has more HP - but is (would be) slower. 
And has over 25% less Nanorange.

Or if u were talking about Veh, as I said u can make 3 Arm vehcons for the cost  of 2 tll vehcons (actually, for even lower cost) and u get 270 vs 230 BP and a lot of other advantages like hp and speed.
